import React from "react";

const Products = [
   {
      id: "1",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "2",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "3",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "4",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "5",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "6",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "7",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "8",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "9",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "10",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "11",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "12",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "13",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "14",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "15",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "16",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "17",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "18",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "19",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "20",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
   {
      id: "21",
      name: "shirt",
      img: "../../assets/img1.jpg",
      price: "999",
      size: "m",
      inStock: "22",
      color: "red",
      category: "men",
   },
];

export default Products;
